### ISSUE TITLE
Ambiguities in _DASH_throughput value. 

### ISSUE THREAD

**Issue by wilaw** [Dash-Industry-Forum/Content-Steering#10]
The player appends a "_DASH_throughput" value to the steering server request.

1. For demuxed content, the players maintains separate estimates of the download rate for video segments and audio segments. Which value should they report via the _DASH_throughput steering server query arg? Suggestion is to use the value derived from the video segments, as these are usually larger and therefore should provide a better estimate of the actual throughput.
2. What if the player had multiperiod content where is playing primary content from "cdn1" and ad content from "ad1". Which one does it report back? If it only reports primary content, then the steering service loses visibility into the performance of "ad1".  One solution would be for the player to combine the pathway and throughput reports using a simple schema like the one below. 

_DASH_=cdn1:38420000,ad2:5140000

which indicates the two pathways that the player has used since it last reported along with the throughput for each.

**Comment by nicoweil** [comment]
Agreed on proposal 2, we need to have visibility on all pathways throughputs.

I tend to agree on proposal 1 too, but we need to add the detail that "if a MPD includes both audio and video representations, the  _DASH_throughput value is the video segments throughput value. In case a MPD includes only audio representations, this value is the audio segments throughput". This is kinda obvious, but better be explicit than implicit.

**Comment by piersoh** [comment]
The definition of the `_DASH_throughput` value could benefit from a more concise description. I realise the definition is drawn from [Apple's steering spec draft](https://developer.apple.com/streaming/HLSContentSteeringSpecification.pdf) but since we're defining a newly named parameter we could enhance the definition somewhat - potential by drawing on the work done in defining the `etp` parameter from [CTA-WAVE CMSD](https://github.com/cta-wave/common-media-server-data). For example one could specify that it be measured over the period of one segment, or a minimum time frame, or an instantaneous measurement derived directly from transport metrics.

**Comment by wilaw** [comment]
I think it would make sense to align `_DASH_throughput `with the semantic meaning that we adopted for CMCD 'mtp' ( measured throughput) property, that is, the throughput value that the player is about to use for its next switching decision. Different players have different algorithms for this (weighted average(s), last segment, transport level, some exotic combination of all three etc) and forcing one in the Content Steering spec is going to cause multiple players to have to synthesize a value that they don't currently maintain. By defining _DASH_throughput in terms of input to the next switching switching decisions, we have a meaningful communication to the steering server.

**Comment by haudiobe** [comment]
call 2022/10/07
- for the first use case, it seems that the higher should  be used (typically the one of the server)
- associating throughput to the pathway/CDN In the response is a good idea, possibly resulting in report of multiple throughputs. Implementation should be done to make it as clean as possible and aligned with what HLS does, if possible.
- Maybe investigate _DASH_pathway to carry multiple parameters.

**Comment by haudiobe** [comment]
call 2022/10/21

- Proposal: create a comma-separated list for the value of the _DASH_throughout_ and _DASH_pathway_ parameters. Is this a better solution? 
- Note that most of the time you only have 1 pathway, so it collapses to original proposal.

Unless there is any feedback within 2 weeks, we accept this.

**Comment by haudiobe** [comment]
Live 2022/11/04

- We believe this breaks some legacy and hence we prefer to only report the last one.
- We still reach out to the ecosystem to address the issue at large in a future revision
-

**Comment by wilaw** [comment]
We never actually got clairity on how to report mutiple pathways and their respective throughputs.

Option #1 
_DASH_pathway="cdn1","cdn4"
_DASH_throughput=4506000,82000000

Option #2 
_DASH_ ="cdn1":4506000,"cdn4":8200000

Option #3 
_DASH_pathway ="cdn1,cdn4"
_DASH_throughput=4506000,82000000

Option #4  - just report the last pathway used and throughput received in order to remain compatible with HLS client reporting. If steering is used to switch Location as well as primary content and ad periods, then this will fail to report Location and ad content steering.

**Comment by wilaw** [comment]
What I have gone ahead and added to the latesat revision is this language


> a. 	The _DASH_pathway parameter shall contain a value of the currently selected BaseURL@serviceLocation, contained in double-quotes. If playback has not yet started due to this being the first request with @queryBeforeStart set to true, then the_DASH_pathway parameter shall be omitted. If multiple serviceLocations are being currently matched, for example in the Location element and in a BaseURL element, or if multiple serviceLocations have been matched since the last steering server request, then all matched serviceLocations shall be listed, separated by a comma delimiter and contained within a single set of double-quotes. 
> 
> b. 	The _DASH_throughput parameter represents a current prediction of media download throughput observed by the client, in units of integer bits per second, from the applied @serviceLocation. The exact method of bit rate estimation may vary by client. If the client has multiple throughput estimates available, for example from demuxed audio and video downloads, then it should report the higher of the available estimates. If playback has not yet started due to this being the first request with @queryBeforeStart set to true, or if the throughput value is unknown for other reasons, then the_DASH_throughput parameter should be omitted. If the _DASH_pathway parameter value references multiple serviceLocations, then the  _DASH_throughput parameter value shall consistent of a comma separated list of throughput values, sequenced such that the n’th item in the _DASH_throughput list applies to the n’th item in the _DASH_pathway list. 

This will result in a steering server call looking something like this:

https://steeringservice.com/app/instance123?token=567&_DASH_pathway="5678,beta,ad2,gamma"&_DASH_throughput=450000,56000000,21000000,32000000

**Comment by haudiobe** [comment]
AHG 2022/12/13

- We agree on option 3.
- Also in case you have different throughput results for audio and video, you should report the larger.
- This is already implemented
