### ISSUE TITLE
Async steering updates via emsg 

### ISSUE THREAD

**Issue by dsilhavy** [Dash-Industry-Forum/Content-Steering#11]
Hi all,
I started to look into content steering in dash.js. Maybe a similar discussion has already come up so please feel free to ignore:

With the current mechanism of using `TTL` the client is making a request to the steering server after a certain time. While this time can change with each response from the steering server it might be reasonable to also trigger async steering requests prior to reaching the time defined by `TTL`.

I was thinking about a similar mechanism that we are already using to enable out of band MPD updates via `emsg` boxes. For instance there could be a DASHEvent with `schemeIdUri` set to `urn:mpeg:dash:contentsteering:2022` and a specific value like `1` that tells the player to trigger a steering request.

I assume this would require a tight integration or at least some link between metrics from the CDN and the packager. So not sure if this really makes sense.

**Comment by wilaw** [comment]
@dsilhavy  - this would be possible, however what use-case does this address? The good thing about current content steering design is that it decouples the steering from the content. This allows a content steering service to steer multiple streams without having to know anything about them. By leveraging in-band messages, the two are now linked. What is the use-case that illustrates the utility of that linkage?

**Comment by dsilhavy** [comment]
@wilaw Thanks for the quick response. I was thinking about a use-case in which a content provider encounters problems with a specific CDN for instance when the load on the CDN increases dramatically in a very short time. The default TTL is set to 300 seconds, maybe some providers use an even higher value. In this case, it might take some time before the client does the next steering request and changes to a different CDN. Using the approach described above a content provider could force the client to do an earlier steering request and switch to a different CDN earlier.
Not sure though if this is really a valid use case.

**Comment by haudiobe** [comment]
2022/10/07

- it binds the steering to the content, which is not a good idea.
- long TTLs may not be a good idea. 
- There should be guidelines for clients that in case of a 404 or a rapid observed throughput change, the client may/should go back the content steering server even before the TTL is expired. The client should still honor TTL in most cases to not overload the ContentSteering Server. Some careful drafting of client behaviour necessary - Input welcome.

**Comment by haudiobe** [comment]
2022/10/21

- we allow the player that a client can switch CDNs in case of problems, ignoring the content server response.
- we request the client to honor the TTL
- unless anyone comes back with a text that would be needed for guidelines, we do nothing

Will be confirmed in 2 weeks unless there is a comment.
