### ISSUE TITLE
DASH MPD extension is not backwards compatible

### ISSUE THREAD

**Issue by poolec** [Dash-Industry-Forum/Content-Steering#14]
The content steering spec draft proposes a new `ContentSteering` element at the top (MPD) level of the DASH MPD.  So far so good.  However, it proposes to insert this into the DASH MPD schema _before_ the existing elements of `MPDtype`.  This is not backwards compatible: MPDs that have a ContentSteering element would not pass schema validation and may break some parsers.  The ordering of elements in xs:sequence is significant.

The ContentSteering element should instead be added _after_ all existing elements of the MPD.  This is necessary whether or not the element is adopted by MPEG.  If it is not adopted by MPEG, then it also needs to be in a separate namespace since the MPD Schema only permits additional elements in other namespaces.

**Comment by haudiobe** [comment]
2022/10/07:

- this seems to be correct, it requires to change the examples. 
- possibly using a different namespace.

**Comment by wilaw** [comment]
Updated Candidate Technical Specification:

1. Adjust MPD schema update to show element being inserted last in the sequence
2. Added text note to indicate that ContentSteering element should be last in series
3. Adjusted all examples. 

Must still decide if we want to release CTS with namespace or not.

**Comment by wilaw** [comment]
At Live Task Force meeting on Dec 2nd  it was decided to release CTS without a custom namespace.

**Comment by haudiobe** [comment]
2022/12/13 ok
