### ISSUE TITLE
Content steering coexistence with DVB DASH BaseURL requirements

### ISSUE THREAD

**Issue by poolec** [Dash-Industry-Forum/Content-Steering#15]
The content steering proposal in some ways complements the BaseURL selection requirements in the DVB profile of DASH ([ETSI TS 103 285](https://www.etsi.org/deliver/etsi_ts/103200_103299/103285/01.03.01_60/ts_103285v010301p.pdf)).  DVB DASH allows for multiple BaseURLs to be prioritised and has some requirements linked to error handling - see clause 10.8.2.1.  This is implemented in dash.js.  ContentSteering at one level provides a useful addition in allowing the BaseURL list and priorities to be changed during a session independently of the MPD.

However, in other ways, Content Steering as proposed is more limited than the DVB DASH approach and as such it could be hard to make use of content steering with a DVB DASH MPD or player.

The main use case relevant here concerns balancing load across more than one CDN.  For example, for cost or capacity reasons a content provider may wish to split the traffic 60% to one CDN and 40% to another.  DVB DASH allows for this using BaseURLs with the same priority and with a 'weight' attribute (rather like DNS).  To achieve this with Content Steering and adjust it over time, it appears you would need to scale the steering server to respond individually to clients, significantly increasing the cost compared to handling a small number of cacheable steering responses varying according to request parameters (which I think covers other use cases).

This use case could be handled by the client if the specification allowed for more than one weighted service location at each priority level.  For example, instead of the example response in A.1, the response could be of the form:

```
{
"VERSION": 1,
"TTL": 300,
"RELOAD-URI": "https://steeringservice.com/app/instance12345?session=abc"
"SERVICE-LOCATION-PRIORITY": [ {{"alpha", 60},{"beta",40}}, {{"alpha", 100}}, {{"beta", 100}} ]
}
```

The client behaviour associated with this would entail:
* choosing between the weighted alternatives at random
* remembering the choice until the service locations or weights change
* responding to errors by looking down the priority list for a service location combination that doesn't include the one that failed

**Comment by haudiobe** [comment]
Call 2022/10/07

- DVB-DASH's weight and client behaviour are not part of MPEG. 
- probably at the time when DVB discusses whether to add `ContentSteering` or not, this issue should be discussed then.
- DVB should just check when this comes to MPEG-DASH, whether any problem would occur.
- We encourage interested DVB members to follow any work in MPEG and raise concerns there if the extension would result in issues or incompatibilities with DVB-DASH.

Adding weights could be considered in an extended VERSION 2, but we also view that an individual weights may not be a relevant case. Weights are likely the same for each client. It would be good to get more feedback on a use case that would require individual weights for each client.

Generally we believe using one or the other is a proposer choice.

**Comment by haudiobe** [comment]
Call 2022/10/21

- Content Steering and DVB-DASH priorities should not be used at the same time because they are two alternative mechanisms to achieve the same goal of load balancing.
- We believe nothing needs to be done in the Content Steering spec at this stage.

Unless we hear differently within 2 weeks, we will close the issue w/o action.

**Comment by wilaw** [comment]
Closing since no further comments received.
