### ISSUE TITLE
Content Steering signaling in MPD

### ISSUE THREAD

**Issue by haudiobe** [Dash-Industry-Forum/Content-Steering#16]
MPEG responds in LS from MPEG#140 (Oct 2022):

_As for the inclusion of MPD signaling for the content steering in the next edition of the MPEG DASH standard, WG3 believes that such an approach would further encourage achieving interoperability across the industry, and therefore we would request technical contributions with the proposed text to be submitted to MPEG Systems for consideration._

A text would be drafted that needs to submitted to MPEG.

**Comment by haudiobe** [comment]
2022/02/12:
- Extensions to MPEG-DASH
  - add `@serviceLocation` to `Location` element
  - add **`ContentSteering`** element to the schema

@haudiobe prepare a draft contribution

**Comment by wilaw** [comment]
Added @serviceLocation to Location element (Schema + semantics) and Content Steering element (Schema. + semantics). 

Also added this language:

> 13.	If the manifest contains one or more Location elements with serviceLocation attributes, then prior to a manifest update, the client shall evaluate the serviceLocation attributes against the PATHWAY-PRIORITY array and select the Location element with the highest matching serviceLocation. If no serviceLocations match then the client may make a default decision about which Location element to select.

**Comment by haudiobe** [comment]
2022/12/13 ok

**Comment by haudiobe** [comment]
We submitted a contribution here: https://members.dashif.org/wg/Interoperability/document/4782?downloadRevision=5090

Prior to feedback, if option is 2 is accepted then a signaling to Content Steering should be added that allows the application or the MPD through a service description to configure whether the client needs to obey the ContentSteering.

**Comment by mikedo** [comment]
I think this is going in the right direction, but it is inappropriate at this time for DASH-IF to document/publish extensions in the MPEG MPD schema namespace.  ISO is not going approve this.  The DASH-IF document needs to be changed to be in the DASH-IF namespace for the time being.  And DASH-IF should submit an input contribution ASAP.  Given the volume of interaction with ISO SC 29 WG3, DASH-IF should become a Cat C liaison so it can make future contributions directly into DMS.

**Comment by haudiobe** [comment]
An agreed solution is available here: https://members.dashif.org/wg/Interoperability/document/4789?downloadRevision=5100

**Comment by haudiobe** [comment]
Feedback
- Response from MPEG: https://members.dashif.org/wg/Liaison/document/4801
- Amd.2: https://members.dashif.org/wg/Liaison/document/4806

@haudiobe will update the spec based on what is agreed in MPEG.

**Comment by haudiobe** [comment]
Addressed in MPEG ISO/IEC 23009-1 5th edition Amd.2 (add a link)
