### ISSUE TITLE
Steering server fail over

### ISSUE THREAD

**Issue by kevleyski** [Dash-Industry-Forum/Content-Steering#18]
At large scale many hits to the content steering server could lead to the resource becoming unavailable (similar to DDoS in nature)

Is there a mechanism to stagger timeout for retries and fail over to alternative servers?

**Comment by wilaw** [comment]
Yes, a smart content server would set custom TTLs for each response. This would flatten a peak request load (say at the start of a game when clients are joining) and shard the retry interval across some timespan (say 200-400s). 

The content steering response does not carry a field for fail over. This might have to be built in to the service fronting the content server.

**Comment by haudiobe** [comment]
2022/12/02

- a separate steering server spec should be done. We recommend to do this in CTA WAVE. 
- we will not fix it here, but defer to CTA WAVE
