### ISSUE TITLE
some question for security and performance

### ISSUE THREAD

**Issue by AUGxhub** [Dash-Industry-Forum/Content-Steering#2]
1 cause it have infos from clients , then the content should not just plain text .. 

related : 6.2 JSON Syntax

Maybe using POST rather than GET ?? 

2 need limit query data length , and limit  query  interval .  cause high frequency http(s)  reporting  will hurt in performance.

3 @proxyServerURL should not process in client side .  any special reason to process it in client ?

**Comment by haudiobe** [comment]
Live TF: 2022/07/15

Observations for item 1:
- https call helps reduce privacy risk 
- no PII is communicated, only operational metrics.
- no action expected

Observations for item 2a:
- minimal data only. 
- But we could give a maximum length for serviceLocation, for example 64 characters.
- Please comment if you have different opinion

Observations for item 2b:
- operational decision
- we should provide some guidance/note that request rate is inversely proportional to TTL.
- Please comment on this, if you have different opinion.

Observations for item 3:
- Thomas to check

**Comment by haudiobe** [comment]
Live TF: 2022/10/21

1) we do nothing on 1 based on the above
2) we restrict serviceLocation to 64 characters
3) @proxyServerURL will be removed,see #13

**Comment by wilaw** [comment]
I defined a new xml schema type for serviceLocation and restricted the length to 64 characters. @proxyServerURL has also been removed from v0.9.5 of community review draft. 

```
<xs:attribute name="serviceLocation">
  <xs:simpleType>
    <xs:restriction base="xs:string">
      <xs:pattern value="[a-zA-Z0-9_.-]"/>
      <xs:maxLength value="64" />
    </xs:restriction>
  </xs:simpleType>
</xs:attribute>
```

**Comment by haudiobe** [comment]
AHG 2022/12/13

- agreed to use this.
- We will ask MPEG to verify this

**Comment by haudiobe** [comment]
MPEG responded with this
- Response from MPEG: https://members.dashif.org/wg/Liaison/document/4801
- Amd.2: https://members.dashif.org/wg/Liaison/document/4806

we need to mandate this in our spec. @haudiobe
