### ISSUE TITLE
add transfer latency information (along with _DASH_throughput and _DASH_pathway) to the parameters sent by the players

### ISSUE THREAD

**Issue by yreznik-brightcove** [Dash-Industry-Forum/Content-Steering#20]
The transmission of _DASH_throughput information alone is insufficient for the steering server to understand what could be causing the loss of bandwidth, and whether a client can sustain continuous playback.
The transmission of transfer latency information (measured for the same transfer as used to compute "throughput") would yield such additional insights. The change in latency can be classified as normal or abnormal for a given CDN and origin configuration,  and the product of throughput*latency would give the size of the last transmitted segment - which could tell the server if the player can still adjust the bitrate to maintain continuous playback. And naturally, if the reported latency is beyond the typical player buffer size (e.g. 30..60sec or minimum declared in the MPD) -- this becomes an indicator that the player has already started buffering. In other words, the transmission of this single additional parameter would bring essential additional information about QOS and QOE to the steering server and would enable it to make more intelligent decisions.  
The request is - please consider adding "_DASH_latency" as an additional standard parameter that can be carried by the players to the steering server.

**Comment by haudiobe** [comment]
AHG 2023/3/3
- Content Steering is not built for instantaneous decisions
- How would the player know the latency?
- Could we send CMCD data to the steering server?
- Could we then remove _DASH_throughput as well and move CMCD?

Proposed resolution:
- no change to spec on DASH_throughput to be compatible with HLS
- we do not change anything to steering server request
- we can a note that content steering could be augmented with real-time data collection (for example CMCD data records) to improve steering decisions. Details are not part of this version of the spec.

@wilaw adds a paragraph along the above lines.

**Comment by haudiobe** [comment]
IOP Live TF 2023/10/3
- Implemented here: https://members.dashif.org/wg/Interoperability/document/4810?downloadRevision=5135 from @wilaw 

OK for final review as part of the IOP review
