### ISSUE TITLE
Comments on version 0.9.7

### ISSUE THREAD

**Issue by dsilhavy** [Dash-Industry-Forum/Content-Steering#21]
Hi all,
some minor comments/questions on version 0.9.7

* Section 7  :  _"13.If the client is playing content defined by a BaseURL element with a `@serviceDescription` not equal to the preferred service location_" : This should probably be `@serviceLocation` instead of `@serviceDescription`
* If a client is not measuring the throughput for manifest downloads what would be the best way to signal this in the `_DASH_throughput` query parameter in case `@serviceLocation` is used for `<Location>`? 
* I suggest to reformat the JSON syntax in 6.2 if possible, it is hard to read.
* In Annex A.2 : Instead of using `ad2` and `gamma` shouldnt this be `ad1` and `delta`: Meaning instead of `https://steeringservice.com/app/instance1234?_DASH_pathway="5678,beta,ad2,gamma"&_DASH_throughput=450000,56000000,21000000,32000000` it is `https://steeringservice.com/app/instance1234?_DASH_pathway="5678,beta,ad1,delta"&_DASH_throughput=450000,56000000,21000000,32000000`

**Comment by haudiobe** [comment]
AHG 2023/04/14


> * Section 7  :  _"13.If the client is playing content defined by a BaseURL element with a `@serviceDescription` not equal to the preferred service location_" : This should probably be `@serviceLocation` instead of `@serviceDescription`

OK, but may change `@serviceLocation` to the term service location in general as defined in amd.2. @haudiobe  

> * If a client is not measuring the throughput for manifest downloads what would be the best way to signal this in the `_DASH_throughput` query parameter in case `@serviceLocation` is used for `<Location>`?

We need a signal for unknown. Options are to not add parameter or to use a defined value such as 0 or _unknown_. @wilaw 

> * I suggest to reformat the JSON syntax in 6.2 if possible, it is hard to read.

ok @haudiobe 

> * In Annex A.2 : Instead of using `ad2` and `gamma` shouldnt this be `ad1` and `delta`: Meaning instead of `https://steeringservice.com/app/instance1234?_DASH_pathway="5678,beta,ad2,gamma"&_DASH_throughput=450000,56000000,21000000,32000000` it is `https://steeringservice.com/app/instance1234?_DASH_pathway="5678,beta,ad1,delta"&_DASH_throughput=450000,56000000,21000000,32000000`

likely ok, need to confirm @wilaw

**Comment by wilaw** [comment]
> If a client is not measuring the throughput for manifest downloads what would be the best way to signal this in the _DASH_throughput query parameter in case @serviceLocation is used for <Location>?

I suggest that the client simply omit the _DASH_throughput parameter from the steering request if the value is unknown or unreliable. It is intended to report the throughput that the client is receiving when accessing that serviceLocation. If the client is fetching only manifests from a given location, then throughput is unlikely to be the main determinant of switching as the requirement is so low compared to that for media segments.

**Comment by wilaw** [comment]
For A2 example, the correction suggested by Daniel is correct. It should be

> _DASH_pathway="5678,beta,ad1,delta"&_DASH_throughput=450000,56000000,21000000,32000000

**Comment by dsilhavy** [comment]
> > If a client is not measuring the throughput for manifest downloads what would be the best way to signal this in the _DASH_throughput query parameter in case @serviceLocation is used for ?
> 
> I suggest that the client simply omit the _DASH_throughput parameter from the steering request if the value is unknown or unreliable. It is intended to report the throughput that the client is receiving when accessing that serviceLocation. If the client is fetching only manifests from a given location, then throughput is unlikely to be the main determinant of switching as the requirement is so low compared to that for media segments.

I missed this when reading through the spec the first time and implemented it accordingly now, thanks. Only thing to consider here I think is to sort the list of `_DASH_throughput` and `_DASH_pathway` accordingly. I assume all the entries without `_DASH_throughput` need to be placed at the end to not mess with the order.

**Comment by haudiobe** [comment]
Implemented here: https://members.dashif.org/wg/Interoperability/document/4810
