### ISSUE TITLE
some suggestion/expanding 

### ISSUE THREAD

**Issue by AUGxhub** [Dash-Industry-Forum/Content-Steering#3]
Cause nowadays most media are from CDN , and CDN some time will have various issue in a extremely low frequency.
but when CDN(server) issue happened, there is no enough info will client can get in touch of them , then client may action in totally wrong solution ,
For example: when CDN is drop request as heavy loading,  but client just got http error code 0 , then client will continue retry , which will make CDN keep in heavy loading ,  then CDN service may enabling Hystrix /fuse/baker mechanism  . 

So , does it possible let steering server summary all CDN statues base session ID (last error/top 99% response process time/top 99% IO speed .etc)  in @ContentSteering 
and these info must  update with same interval , when client request steering server .

**Comment by haudiobe** [comment]
Live TF: 2022/10/21

Thanks for the issue

Unfortunately we were not fully able to understand the issue. However, we understand that more information from the server would be requested. We believe that at least in the initial version, this is outside the scope of the specification and we prefer simplicity and compatibility with HLS. However, we point the poster to the CTA WAVE CMSD specification: 
https://github.com/cta-wave/common-media-server-data

We will close this in the next TF meeting in 2 weeks unless there substantially different information being provided.
