### ISSUE TITLE
Assumption that MPD and media segments come from same CDN

### ISSUE THREAD

**Issue by glenng1215gh** [Dash-Industry-Forum/Content-Steering#4]
It's a minor point, but I see in section 4(the introduction) the following statement:

"The provider also uploads the MPD and the Content segments to both CDNs. At the start of playback, the DASH client requests the MPD from one CDN.." 

This assumes that both MPDs and media segments are distributed via the same CDN. In some cases (such as SSAI), MPDs may be dynamically generated and served via different CDNs and hostnames than the media segments.

I don't think it impacts the specification, but you may want to consider updating that language, along with figure 4-2 which indicates MPDs being uploaded to CDN1 and CDN2.

**Comment by haudiobe** [comment]
Live TF 2022/10/21

Thank you for your comment.

We added the ability to steer the manifest. This should address the issue. 

We close the issue.
