### ISSUE TITLE
What to put as a _DASH_pathway query parameter when multiple ServiceLocation are "used" at the same time

### ISSUE THREAD

**Issue by peaBerberian** [Dash-Industry-Forum/Content-Steering#6]
Hi,

I'm a DASH player developer at Canal+ (on the open-sourced RxPlayer project) and we're currently looking to implement Content-Steering to answer situations where deterministic CDN switching would be very useful.

I have a question regarding the `_DASH_pathway` query parameter that is used to signal which ServiceLocation is currently used by the player, to the DCSM server / proxy:
What should a DASH player put in the `_DASH_pathway` query parameter if multiple ServiceLocation are used depending on the AdaptationSet, Representation and/or Period?

Especially a real life scenario might be choosing a different ServiceLocation for audio and video AdaptationSet, for example because a different set of ones are available for the two in the MPD.

---

As a proposal, an optional list of ServiceLocation may here be more appropriate. I could see several ways of implementing this, though they still have some disadvantages:
  - For example, a player could just having a token-separated list (with the token in question to be defined) of ServiceLocation in the `_DASH_pathway` query parameter. But it would not communicate the information of which ServiceLocation is used for what media (i.e. which one is for the audio track etc.).
  - Having separate, more precise, query parameter (e.g. `_DASH_pathway_audio`, `_DASH_pathway_video`, `_DASH_pathway_text`) may be nice though I'm unsure if a player could e.g. display several text tracks at the same time.
     There it would move the issue further (though I admit that this is a really small edge case). I'm also unsure right now if the named set of "type" of media (audio, video, text, metadata and so on) based on MPD attributes is really defined somewhere.

    Sorry if I'm writing about complex use cases without real life examples by the way, as a player developer (moreover open-source, as people sometimes like to load very exotic MPDs!), we generally have to specify a behavior under those cases anyway, so we like to ask those weird questions!
    _(I would still understand if complex and rare situations are not handled for the sake of simplicity, though I for now consider that an explicit sentence indicating either non-support or leading to an undefined behavior would be better to make it clear for potential future cases where it really comes up.)_
    
    I however still think that the base issue of having a different set of ServiceLocation for a chosen audio and video AdaptationSet might be a real and frequent enough use case.

**Comment by haudiobe** [comment]
Live TF 2022/10/21

Thank you for your comment.

This seems to be a valid issue. Related issue is #10. 

We believe the multiple parameters object proposed in #10 would resolve this.
Unless we hear differently within the next 2 weeks, we would close the issue and point to the solution in #10.

**Comment by haudiobe** [comment]
Live TF 2022/11/04

No comments received. We take the solution in #10. 

Thank you

**Comment by wilaw** [comment]
In the latest draft I suggest that we report it like this

https://steeringservice.com/app/instance1234?_DASH_pathway="5678,beta,ad2,gamma"&_DASH_throughput=450000,56000000,21000000,32000000

**Comment by haudiobe** [comment]
Closed with #10
