### ISSUE TITLE
Error in example for includeInRequests value

### ISSUE THREAD

**Issue by wilaw** [Dash-Industry-Forum/Content-Steering#7]
In Sect 8.1, the includeInRequests attribute incorrectly passes a string value instead of a number. 

Currently

`<up:ExtUrlQueryInfo   queryTemplate="token=$query:steeringToken$"   useMPDUrlQuery="true" includeInRequests="steering"/>  </up:ExtUrlQueryInfo>`

should be

`<up:ExtUrlQueryInfo   queryTemplate="token=$query:steeringToken$"   useMPDUrlQuery="true" includeInRequests="7"/>  </up:ExtUrlQueryInfo>`

**Comment by technogeek00** [comment]
Actually double checked this, it should be:

```xml
<up:ExtUrlQueryInfo queryTemplate="token=$query:steeringToken$" useMPDUrlQuery="true" includeInRequests="steering"/> </up:ExtUrlQueryInfo>
```

The keys are the string names in the spec, confirmed by the XML Syntax

```xml
<xs:element name="ExtUrlQueryInfo" type="ExtendedUrlInfoType"/>
<xs:element name="ExtHttpHeaderInfo" type="ExtendedUrlInfoType"/>
<xs:complexType name="ExtendedUrlInfoType">
    <xs:complexContent>
        <xs:extension base="UrlQueryInfoType">
            <xs:attribute name="includeInRequests" type="xs:string" default="segment"/>
            <xs:attribute name="headerParamSource" type="xs:string" default=""/>
            <xs:attribute name="sameOriginOnly" type="xs:boolean" default="false"/>
        </xs:extension>
    </xs:complexContent>
</xs:complexType>
```

This also means in the proposal section 8.2.2 we need to change this:
> 7) "content steering" (requests to Content Steering servers)

to this:
> 7) "steering" (requests to Content Steering servers)

**Comment by wilaw** [comment]
Change made to drafty v0.9.5 of community review spec.

**Comment by haudiobe** [comment]
2022/12/13 ok
