### ISSUE TITLE
Add the ability to steer the manifest 

### ISSUE THREAD

**Issue by wilaw** [Dash-Industry-Forum/Content-Steering#8]
The current solution uses BaseURL to steer requests for audio, video and timed-text . However this approach is unable to steer the manifest requests to a new source. Given that delivering manifests from a different source than the media segments is a common requirement for SSAI solutions, a comprehensive DASH steering solution needs to have the ability to also steer the manifests to load from a new location.

Below we propose a method for how this can be done. Manifests can be reloaded via the MPD.Location element, which holds the URI pointing to the new source for the manifest. MPD.Location elements are allowed in  the manifest. We add a label attribute to the MPD.Location element, which now allows steering. We add a rule that Location element labels and BaseURL serviceLocation descriptors MUST be unique with a manifest

```
<MPD ... >
    <Location label="mpd1">https://ssai1.com/manifest.mpd</Location>
    <Location label="mpd2">https://ssai2.com/manifest.mpd</Location>
    <BaseURL serviceLocation="segments1">http://cdn3.com/</BaseURL>
    <BaseURL serviceLocation="segments2">http://cdn4.com/</BaseURL>
    <ContentSteering defaultServiceLocation="alpha">https://steeringservice.com/app/instance1234</ContentSteering>
    <Period .../>
</MPD
```

The Steering server then returns

```
{
   "VERSION": 1,
   "TTL": 300,
   "RELOAD-URI": "https://steeringservice.com/app/instance12345?session=abc"
   "SERVICE-LOCATION-PRIORITY": ["mpd2","segments2"]
}
```

The player evaluates each of the Location.label identifiers to see if they match the highest priority item in the SERVICE-LOCATION-PRIORITY array. In this case, "mpd2" matches, and so the player will reload the manifest at the next scheduled manifest reload from https://ssai2.com/manifest.mpd. The player then evaluates each of the BaseURL serviceLocations. Since mpd2 is not present in any of the BaseURLs, it does not match. The first match it finds is "segments1" and therefore it switches to pulling segments from http://cdn4.com/. 

Questions:
1. Since SERVICE-LOCATION-PRIORITY will hold both BaseURL serviceLocations and Location labels, should we rename it? Would a return to the HLS name of PATHWAY-PRIORITY be appropriate? 
2. Should Location.label instead be Location.serviceLocation for consistency with BaseURL? IN this way we can talk consistently about steering between serviceLocations instead of serviceLocations and labels.

**Comment by nicoweil** [comment]
Agreed on point 2: Location@label introduces a confusing asymmetry.

On point 1 I'm not sure: if we want to combine both HLS and DASH steering in a single steering server response, there will be a naming conflict.

**Comment by haudiobe** [comment]
AHG 2022/07/15

- Agree with basic proposal
- Agree with comment from @nicoweilelemental - make it `@serviceLocation`
- Please comment if you have different opinion

- Discussion: What other URLs are available in the MPD? Examples: xlink, keys
  - do we want to make these steerable as well?
  - Please comment if you believe you want to have more steering URLs
  - General design: keep single manifest, location customization. We may need per Period instructions - see #4

**Comment by haudiobe** [comment]
Live TF 2022/10/21

In the absence of knowledge of deployments for xlink etc, we believe that for the initial version the steering of other URLs is not needed. Hence we go ahead with the first two proposals above

-  Agree with basic proposal
-  Agree with comment from @nicoweilelemental - make it `@serviceLocation`

**Comment by wilaw** [comment]
Added changes to 0.9.5 of draft spec, including prose and updates to the DASH XML schema.  Also added an example A2 to illustrate manifest steering.

**Comment by haudiobe** [comment]
2022/12/13 ok
