### ISSUE TITLE
How to steer ads separately from primary content?

### ISSUE THREAD

**Issue by wilaw** [Dash-Industry-Forum/Content-Steering#9]
The current design assumes a single set of BaseURL options at the root level, applying to all periods. However in the real world, we are likely to have multi-period content where some of the periods hold ads. These ads are often served by different CDNs to those who serve the primary content. We'd like to be able to steer the ad content as well as the primary content. 

We think this requirement can be solved quite simply if the spec is updated to say:
1. BaseURLs should be applied at the period level for those periods holding advertising content
3. As it enters a period, the player should evaluate the BaseURLs serviceLocations against the last steering server response. 
4. The steering response can return an intermixed array of primary and ad serviceLocations.

Example manifest

```
<MPD ... >
    <BaseURL serviceLocation="segments1">http://cdn1.com/</BaseURL>
    <BaseURL serviceLocation="segments2">http://cdn2.com/</BaseURL>
    <ContentSteering defaultServiceLocation="alpha">https://steeringservice.com/app/instance1234</ContentSteering>
    <Period ...(ad)>
             <BaseURL serviceLocation="ad1">http://adcdn1.com/</BaseURL>
             <BaseURL serviceLocation="ad2">http://adcdn2.com/</BaseURL>
             ...
    </Period>
    <Period ... (primary content)/> 
    <Period ...(ad)>
             <BaseURL serviceLocation="ad1">http://cdn1.com/</BaseURL>
             <BaseURL serviceLocation="ad2">http://cdn2.com/</BaseURL>
             ...
    </Period>
    <Period ... (primary content)/> 
    <Period ...(ad)>
             <BaseURL serviceLocation="ad3">http://adcdn1.com/</BaseURL>
             <BaseURL serviceLocation="ad4">http://adcdn4.com/</BaseURL>
             ...
    </Period>
</MPD
```

The steering server could then specify

```
{
   "VERSION": 1,
   "TTL": 300,
   "RELOAD-URI": "https://steeringservice.com/app/instance12345?session=abc"
   "SERVICE-LOCATION-PRIORITY": ["segments2","ad3","ad2","segments1","ad1","ad4"]
}
```

Note that segments1, ad1 and ad3 all point at cdn1.com, however by assigning them different service locations, we can steer content towards or away from cdn1.com separately depending on whether it is ad or primary content and also depending on which period it is in. 

Question - to ensure that the SERVICE-LOCATION-PRIORITY is fresh, should we introduce a TTL option rule in which the steering server should always be called just prior to entering a new period?

**Comment by nicoweil** [comment]
This works. I like the idea of refreshing the SERVICE-LOCATION-PRIORITY data when entering a new period. However, this is gonna be difficult to support it through the TTL value modification. I think we should make sure that there is a client implementation recommendation saying something like "when the end of a period is detected in the MPD, force a call to the steering server". It might trigger an intense wave of requests to the steering server roughly at the same time, but I think it's fine, as a steering service is anyways gonna need to be a highly scalable service.

**Comment by haudiobe** [comment]
Live TF 2022/10/11

- Agree with the basic solution
- DASH Players should revalidate the ContentSteering server everytime you switch BaseURL that is not caused by a ContentSteering response, i.e. when the content is not available on the current CDN. This also resets the TTL clock.

Please comment within 2 weeks, otherwise we implement.

**Comment by haudiobe** [comment]
Live TF 2022/11/04

- This may cause a problem, namely it synchronizes the requests from the time there is a Period switching to a new CDN.
- We will not add the statement on CDN switches

**Comment by wilaw** [comment]
Adding example A2 illustrating the  independent steering of manifests, media segments and advertising content.

**Comment by haudiobe** [comment]
2022/12/13 ok
